### ISSUE TITLE
Решарпером упорно не пользуешься :)

### ISSUE THREAD

**Issue by hisubbotin** [Avetome/TransformEquationToCanonical#1]
https://github.com/Avetome/TransformEquationToCanonical/blob/86d09eaa91838f3acbd717513070a1d7ab9eb07c/EquationTransformer/Summand.cs#L109

**Comment by hisubbotin** [comment]
Точно ли тут надо использовать double?

**Comment by avetome** [comment]
Увы, у меня его нет. Покупать жаба давит, брать с рутрекера тоже не хочется.

**Comment by avetome** [comment]
А насчет типа. Если не double, то float или decimal. 

Float занимает меньше памяти, но и менее точен (6-9 цифр). Decimal более точен, но и занимает в памяти в два раза больше места. Double выглядит как компромисс )

Плюс, популярный ответ на SO рекомендует для "values which are more artefacts of nature" использовать double. А поскольку задача тут про уравнения, то хочется думать, что уравнения эти для чего-то научного, например для расчета новых фотографий черной дыры, чем для подсчета чего-то скучного и финансового ))
