### ISSUE TITLE
Close точно нужны, если ты прям сразу же делаешь Dispose? 

### ISSUE THREAD

**Issue by hisubbotin** [Avetome/TransformEquationToCanonical#2]
https://github.com/Avetome/TransformEquationToCanonical/blob/86d09eaa91838f3acbd717513070a1d7ab9eb07c/EquationTransformer/Program.cs#L105

**Comment by avetome** [comment]
Упс, да. Close не нужен, using есть. Видимо, первоначальный вариант был без using, потом добавил, а Close убрать забыл.

**Comment by avetome** [comment]
Пофиксил в https://github.com/Avetome/TransformEquationToCanonical/commit/9a7116101c9f12fec6c9e8a37fca782b517e4df9
