### ISSUE TITLE
Зачем делать IEnumerable, если можно в theory передать две строки просто? 

### ISSUE THREAD

**Issue by hisubbotin** [Avetome/TransformEquationToCanonical#3]
https://github.com/Avetome/TransformEquationToCanonical/blob/86d09eaa91838f3acbd717513070a1d7ab9eb07c/EquationTransformerTests/EquationTransformerTests.cs#L39

**Comment by hisubbotin** [comment]
Прям первый же пример: http://hamidmosalla.com/2017/02/25/xunit-theory-working-with-inlinedata-memberdata-classdata/
с InlineData

**Comment by hisubbotin** [comment]
Субъективно тесты после рефакторинга выглядят не очень и дублирование кода перешло из одного места в другое (генерация ienumerable). Кажется, что этот код может быть сильно проще

**Comment by avetome** [comment]
Не хотел использовать InlineData просто потому, что бы можно было хранить тесты в отдельном методе для большей расширяемости. Что бы была возможность, например, читать примеры из отдельного файла. 

С InlineData да, выглядеть будет проще, спору нет.

**Comment by hisubbotin** [comment]
То есть ради расширяемости увеличил кодовую базу раза в 3 :) ну ок

**Comment by avetome** [comment]
Всегда есть пути упрощения, но они зависят от деталей реального приложения. 

Можно, например, сделать вот так: #7
