### ISSUE TITLE
x + y = 1

### ISSUE THREAD

**Issue by hisubbotin** [Avetome/TransformEquationToCanonical#4]
https://github.com/Avetome/TransformEquationToCanonical/blob/86d09eaa91838f3acbd717513070a1d7ab9eb07c/EquationTransformerTests/EquationTransformerTests.cs#L55

**Comment by avetome** [comment]
Пофиксил в https://github.com/Avetome/TransformEquationToCanonical/commit/e141e1f0ae060fff749d8bc1c2139d529a332fb9
