### ISSUE TITLE
Объединение бизнес-логики с консольным проектом в один на мой взгляд не очень.

### ISSUE THREAD

**Issue by hisubbotin** [Avetome/TransformEquationToCanonical#5]
https://github.com/Avetome/TransformEquationToCanonical/blob/86d09eaa91838f3acbd717513070a1d7ab9eb07c/EquationTransformer/Parser.cs#L8

**Comment by avetome** [comment]
Полностью согласен. Но это же тестовое задание, а не реальное приложение. Соответственно, есть определенные допущения. Поэтому я решил не разделять.
